import Head from 'next/head'
import Form from './Form'

export default function Home() {
  return (
    <div>
      <Head>
        <title>User Creation App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Form/>
      </main>
    </div>
  )
}
